import type { ResourceDef } from '../types.js'
import {
  DOCS_CHARGES_URL,
  DOCS_LINKS_URL,
  DOCS_PAYMENT_INTENTS_URL,
  DOCS_TRANSFERS_OBJECT_URL,
} from '../lib/constants.js'

export const resources: ResourceDef[] = [
  {
    name: 'payment_intents',
    displayName: 'payment intent',
    cliCommand: 'payment_intents',
    sdkMethod: 'paymentIntents',
    sdkNamespace: 'v1',
    verbs: ['get', 'list'],
    priorityColumns: ['id', 'amount', 'currency', 'status', 'created_at'],
    listFlags: [
      {
        name: 'status',
        type: 'string',
        description: `Filter by status (see ${DOCS_PAYMENT_INTENTS_URL})`,
      },
      {
        name: 'since',
        type: 'string',
        description: 'Show results created after this date (ISO 8601)',
      },
      {
        name: 'until',
        type: 'string',
        description: 'Show results created before this date (ISO 8601)',
      },
    ],
  },
  {
    name: 'transfers',
    displayName: 'transfer',
    cliCommand: 'transfers',
    sdkMethod: 'transfers',
    sdkNamespace: 'v2',
    verbs: ['create', 'get', 'list'],
    needsJws: true,
    priorityColumns: ['id', 'amount', 'currency', 'status', 'transaction_date'],
    createFlags: [
      {
        name: 'amount',
        type: 'integer',
        required: true,
        description: 'Amount in smallest currency unit',
      },
      {
        name: 'currency',
        type: 'string',
        required: true,
        description: 'Currency code (CLP, MXN)',
      },
      {
        name: 'account-id',
        type: 'string',
        required: true,
        description: 'Account ID the money should come out of',
      },
      {
        name: 'counterparty-account-number',
        type: 'string',
        required: true,
        description: 'Destination account number',
        nestedPath: 'counterparty.account_number',
      },
      {
        name: 'counterparty-institution-id',
        type: 'string',
        required: true,
        description: 'Destination bank institution ID (e.g., cl_banco_estado)',
        nestedPath: 'counterparty.institution_id',
      },
      {
        name: 'counterparty-holder-id',
        type: 'string',
        description: 'Counterparty holder ID (e.g., RUT in Chile, required for CL)',
        nestedPath: 'counterparty.holder_id',
      },
      {
        name: 'counterparty-account-type',
        type: 'string',
        description: 'Counterparty account type (checking_account, sight_account, required for CL)',
        nestedPath: 'counterparty.account_type',
      },
      {
        name: 'comment',
        type: 'string',
        description: 'Reference visible to the recipient',
      },
    ],
    listFlags: [
      {
        name: 'status',
        type: 'string[]',
        description: `Filter by status (see ${DOCS_TRANSFERS_OBJECT_URL})`,
      },
      {
        name: 'since',
        type: 'string',
        description: 'Show results created after this date (ISO 8601)',
      },
      {
        name: 'until',
        type: 'string',
        description: 'Show results created before this date (ISO 8601)',
      },
    ],
  },
  {
    name: 'accounts',
    displayName: 'account',
    cliCommand: 'accounts',
    sdkMethod: 'accounts',
    sdkNamespace: 'v2',
    verbs: ['get', 'list'],
    priorityColumns: [
      'id',
      'entity.holder_name',
      'currency',
      'available_balance',
      'status',
      'refreshed_at',
    ],
    listFlags: [{ name: 'type', type: 'string', description: 'Filter by account type' }],
  },
  {
    name: 'webhook_endpoints',
    displayName: 'webhook endpoint',
    cliCommand: 'webhook_endpoints',
    sdkMethod: 'webhookEndpoints',
    sdkNamespace: 'v1',
    verbs: ['create', 'get', 'list', 'delete'],
    priorityColumns: ['id', 'name', 'url', 'status', 'created_at'],
    createFlags: [
      {
        name: 'url',
        type: 'string',
        required: true,
        description: 'Endpoint URL to receive webhooks',
      },
      {
        name: 'enabled-events',
        type: 'string[]',
        required: true,
        description: 'Events to subscribe to (comma-separated)',
      },
      { name: 'description', type: 'string', description: 'Description of the webhook endpoint' },
    ],
    listFlags: [],
  },
  {
    name: 'charges',
    displayName: 'charge',
    cliCommand: 'charges',
    sdkMethod: 'charges',
    sdkNamespace: 'v1',
    verbs: ['create', 'get', 'list'],
    priorityColumns: ['id', 'amount', 'currency', 'status', 'created_at'],
    createFlags: [
      {
        name: 'amount',
        type: 'integer',
        required: true,
        description: 'Amount in smallest currency unit',
      },
      {
        name: 'currency',
        type: 'string',
        required: true,
        description: 'Currency code (e.g., CLP)',
      },
      {
        name: 'subscription-id',
        type: 'string',
        required: true,
        description: 'Subscription ID to charge',
      },
    ],
    listFlags: [
      {
        name: 'status',
        type: 'string',
        description: `Filter by status (see ${DOCS_CHARGES_URL})`,
      },
      {
        name: 'since',
        type: 'string',
        description: 'Show results created after this date (ISO 8601)',
      },
      {
        name: 'until',
        type: 'string',
        description: 'Show results created before this date (ISO 8601)',
      },
      {
        name: 'subscription-id',
        type: 'string',
        description: 'Filter by subscription ID',
      },
    ],
  },
  {
    name: 'subscriptions',
    displayName: 'subscription',
    cliCommand: 'subscriptions',
    sdkMethod: 'subscriptions',
    sdkNamespace: 'v1',
    verbs: ['get', 'list'],
    priorityColumns: [
      'created_at',
      'id',
      'account.holder_name',
      'account.holder_id',
      'account.institution',
      'status',
    ],
    listFlags: [
      {
        name: 'since',
        type: 'string',
        description: 'Show results created after this date (ISO 8601)',
      },
      {
        name: 'until',
        type: 'string',
        description: 'Show results created before this date (ISO 8601)',
      },
    ],
  },
  {
    name: 'links',
    displayName: 'link',
    cliCommand: 'links',
    sdkMethod: 'links',
    sdkNamespace: 'v1',
    verbs: ['get', 'list', 'delete'],
    priorityColumns: ['id', 'holder_id', 'institution', 'status', 'created_at'],
    getArg: {
      name: 'link_token',
      description: `Link token (format: LINK_ID_token_LINK_ACCESS_TOKEN, see ${DOCS_LINKS_URL})`,
    },
    listFlags: [
      {
        name: 'status',
        type: 'string',
        description: `Filter by status (see ${DOCS_LINKS_URL})`,
      },
    ],
  },
  {
    name: 'checkout_sessions',
    displayName: 'checkout session',
    cliCommand: 'checkout_sessions',
    sdkMethod: 'checkoutSessions',
    sdkNamespace: 'v1',
    verbs: ['create', 'get', 'expire'],
    priorityColumns: ['id', 'amount', 'currency', 'status', 'created_at'],
    createFlags: [
      {
        name: 'amount',
        type: 'integer',
        required: true,
        description: 'Amount to pay in smallest currency unit (must be > 0 and < 7000000)',
      },
      {
        name: 'currency',
        type: 'string',
        required: true,
        description: 'Currency code (CLP, MXN)',
      },
      {
        name: 'success-url',
        type: 'string',
        description: 'Redirect URL after successful payment',
      },
      {
        name: 'cancel-url',
        type: 'string',
        description: 'Redirect URL if customer cancels',
      },
      {
        name: 'customer-email',
        type: 'string',
        description: 'Customer email for refund notifications',
      },
      {
        name: 'recipient-account-type',
        type: 'string',
        description: 'Recipient account type (checking_account, sight_account)',
        nestedPath: 'payment_method_options.payment_intent.recipient_account.type',
      },
      {
        name: 'recipient-account-number',
        type: 'string',
        description: 'Recipient account number',
        nestedPath: 'payment_method_options.payment_intent.recipient_account.number',
      },
      {
        name: 'recipient-account-holder-id',
        type: 'string',
        description: 'Recipient account holder ID (e.g., RUT in Chile)',
        nestedPath: 'payment_method_options.payment_intent.recipient_account.holder_id',
      },
      {
        name: 'recipient-account-institution-id',
        type: 'string',
        description: 'Recipient bank institution ID (e.g., cl_banco_estado)',
        nestedPath: 'payment_method_options.payment_intent.recipient_account.institution_id',
      },
      {
        name: 'business-profile-tax-id',
        type: 'string',
        description: 'Merchant tax ID (e.g., RUT in Chile)',
        nestedPath: 'business_profile.tax_id',
      },
      {
        name: 'business-profile-name',
        type: 'string',
        description: 'Merchant display name',
        nestedPath: 'business_profile.name',
      },
      {
        name: 'business-profile-category',
        type: 'string',
        description: 'Merchant activity code (6 characters in Chile)',
        nestedPath: 'business_profile.category',
      },
    ],
    listFlags: [],
  },
  {
    name: 'api_keys',
    displayName: 'API key',
    cliCommand: 'api_keys',
    sdkMethod: 'apiKeys',
    sdkNamespace: 'v1',
    verbs: ['list'],
    priorityColumns: ['token', 'mode', 'is_public', 'created_at'],
    listFlags: [],
  },
]

export const v1Resources = resources.filter((r) => r.sdkNamespace === 'v1')
export const v2Resources = resources.filter((r) => r.sdkNamespace === 'v2')
